### ISSUE TITLE
模型训练的代码方便放出来吗

### ISSUE THREAD

**Issue by changleilei** [sunyilgdx/NSP-BERT#1]
给的模型连接，是你们已经训练好的吗？

**Comment by sunyilgdx** [comment]
您好，模型是从由Google, UER, 和HFL等机构训练的原始BERT模型，只要经过NSP任务预训练就可以，不是我们自己训练的

**Comment by chenhaoenen** [comment]
@sunyilgdx 首先感谢大佬的项目，
您的意思是不是，不需要训练了已经，也甚至不需要 finetuning , 直接down 网上开元的预训练的model就ok吗？
比如说文本分类问题：
只需要把训练数据制作成对应的pattern, 然后输入到预训练model中，比较[CLS]的概率就ok吗？

**Comment by sunyilgdx** [comment]
是的，不需要任何训练
是把验证集和测试集数据与prompt template做成句子对，输入到模型中
同时，不是[CLS]的概率，是[CLS]连接的NSP head的输出概率
@chenhaoenen

**Comment by chenhaoenen** [comment]
感谢回复！！！ 厉害了大佬， amazing work !
