### ISSUE TITLE
The forecast is too slow

### ISSUE THREAD

**Issue by rgzn-aiyun** [sunyilgdx/NSP-BERT#4]
Each forecast requires the loading of a template? Too long the template leads to an increase in the forecast time!

**Comment by sunyilgdx** [comment]
This is indeed a current problem, and there may be many ways to optimize it, all of which can be used as future research directions.

**Comment by rgzn-aiyun** [comment]
> This is indeed a current problem, and there may be many ways to optimize it, all of which can be used as future research directions.

Can local templates be loaded to memory so that there is no need to regenerate templates?

**Comment by sunyilgdx** [comment]
Not work for BERT, unless you use siamese network.
