### ISSUE TITLE
做下一句预测应该怎么做？

### ISSUE THREAD

**Issue by ZhuShengchen** [sunyilgdx/NSP-BERT#5]
hi，想做下一句预测的任务应该怎么做，比如给出两个句子，预测第二句是第一句的下句的概率，应该怎么做呢？

**Comment by sunyilgdx** [comment]
NSP就是这个任务啊

**Comment by ZhuShengchen** [comment]
但是没有放出训练代码，具体如何实现的呢？

**Comment by sunyilgdx** [comment]
NSP是BERT的预训练任务，本项目目前没有相关的finetune代码，需要将预训练的代码进行改造，似乎难度也不大
