### ISSUE TITLE
可以增加few-shot的代码吗？

### ISSUE THREAD

**Issue by Maskyyds** [sunyilgdx/NSP-BERT#7]
nsp-bert能zero样本应该也能少样本训练，不知道能不能提供代码

**Comment by sunyilgdx** [comment]
早已准备好了，但是还需要等一段时间才能上传

**Comment by sunyilgdx** [comment]
> 



> nsp-bert能zero样本应该也能少样本训练，不知道能不能提供代码

早已准备好了，但是还需要等一段时间才能上传
改动可能比较大，可能准备重新开一个仓库，请关注

**Comment by sunyilgdx** [comment]
> 

代码放到了新仓库
https://github.com/sunyilgdx/Prompts4Keras
